/**
 * Research Participation Service
 *
 * Handles submission of research participant data and exports analysis reports.
 * Currently a stub that logs to console - ready to wire to backend.
 *
 * Backend options:
 * - Google Sheets API
 * - Airtable
 * - Custom API endpoint
 * - Email service (SendGrid, Mailgun)
 */

export async function submitResearchParticipant(participantData) {
  // participantData shape:
  // {
  //   email: string,
  //   role: string,
  //   teamSize: string,
  //   challenge: string (optional),
  //   documentName: string,
  //   documentText: string (full original text),
  //   analysisData: {
  //     clauses: [...],      // Full clause objects with explanations
  //     suggestions: [...],  // Full suggestion objects
  //     comments: {...}      // User's notes
  //   },
  //   timestamp: ISO string
  // }
  //
  // IMPORTANT: Must save clauses + suggestions exactly as shown to user
  // (not regenerate via API later - costs money + non-deterministic results)

  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1000));

  // Log participant data for manual Google Sheets entry (v1)
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('🎯 NEW RESEARCH PARTICIPANT');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('Email:', participantData.email);
  console.log('Role:', participantData.role);
  console.log('Team Size:', participantData.teamSize);
  console.log('Challenge:', participantData.challenge || '(not provided)');
  console.log('Document:', participantData.documentName);
  console.log('Timestamp:', new Date(participantData.timestamp).toLocaleString());
  console.log('');
  console.log('Analysis Summary:');
  console.log('- Clauses analyzed:', participantData.analysisData.clauses.length);
  console.log(
    '- Suggestions generated:',
    participantData.analysisData.suggestions.length
  );
  console.log(
    '- Comments added:',
    Object.keys(participantData.analysisData.comments).length
  );
  console.log('');
  console.log('Full participant data object:');
  console.log(JSON.stringify(participantData, null, 2));
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  // TODO: Optional - Add Slack webhook notification
  // await notifySlack(participantData);

  // TODO: Optional - Send email with analysis
  // await sendAnalysisEmail(participantData);

  // Simulate success response
  return {
    success: true,
    message: "Analysis sent! We'll contact you within 48 hours.",
  };
}

export async function exportAnalysisText(documentName, clauses, suggestions, comments) {
  // Returns plain text analysis (upgrade to PDF via expo-print later if needed)

  const text = `
CONTRACT ANALYSIS REPORT
Document: ${documentName}
Generated: ${new Date().toLocaleDateString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CLAUSES ANALYZED (${clauses.length} total)

${clauses
  .map(
    (c, i) => `
${i + 1}. ${c.title.toUpperCase()}
   Importance: ${c.importance}

   ${c.explanation}

   Key Points:
${c.keyPoints.map((p) => `   • ${p}`).join('\n')}
`
  )
  .join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUGGESTED IMPROVEMENTS (${suggestions.length} total)

${suggestions
  .map(
    (s, i) => `
${i + 1}. ${s.title.toUpperCase()}
   Priority: ${s.priority} | Category: ${s.category}

   Issue Found:
   ${s.issue}

   Why This Matters:
   ${s.reason}

   Recommended Change:
   ${s.recommendedChange}

   Expected Benefits:
${s.benefits.map((b) => `   ✓ ${b}`).join('\n')}
`
  )
  .join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

YOUR NOTES

${
  Object.entries(comments).length === 0
    ? '(No comments added)'
    : Object.entries(comments)
        .map(([clauseId, cmts]) => {
          const clauseTitle =
            clauseId === 'general'
              ? 'GENERAL NOTES'
              : clauses.find((c) => c.id === clauseId)?.title.toUpperCase() ||
                clauseId;
          return `${clauseTitle}:\n${cmts.map((c) => `  • ${c.text}`).join('\n')}`;
        })
        .join('\n\n')
}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This analysis was generated by Contract Analyzer.
Questions? Reply to our research outreach email.
  `.trim();

  return text;
}

// Optional: Slack webhook notification (Phase 8)
// Uncomment and add your webhook URL to enable
/*
const SLACK_WEBHOOK_URL = 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL';

async function notifySlack(participantData) {
  const message = {
    text: '🎯 New Research Participant!',
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*New research participant submitted!*\n\n*Email:* ${participantData.email}\n*Role:* ${participantData.role}\n*Team Size:* ${participantData.teamSize}\n*Challenge:* ${participantData.challenge || '(not provided)'}\n*Document:* ${participantData.documentName}\n*Timestamp:* ${new Date(participantData.timestamp).toLocaleString()}`,
        },
      },
    ],
  };

  try {
    const response = await fetch(SLACK_WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(message),
    });

    if (!response.ok) {
      console.error('Slack notification failed:', response.statusText);
    }
  } catch (error) {
    console.error('Error sending Slack notification:', error);
  }
}
*/
